---
name: 'Close stale issues and PRs'
# https://github.com/actions/stale
on:
  workflow_call:    # Allows you to run this workflow manually from the Actions tab

jobs:
  Stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # debug-only: true
          # start-date: 2025-03-18T00:00:00Z
          # If set to true, the issues or the pull requests with a milestone will not be marked as stale automatically.
          exempt-all-milestones: true
          # If set to true, the issues or the pull requests with an assignee will not be marked as stale automatically.
          exempt-all-assignees: true

          days-before-stale: 0

          # Issue
          # days-before-issue-stale: 60
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-issue-label: Stale

          # days-before-issue-close: 10
          close-issue-message: 'This issue was closed because it has been stalled for 10 days with no activity.'
          close-issue-label: Stale

          exempt-issue-labels: 4 - verified,4 - internal Issue/MR,3 - wait for merge,3 - wait for pipeline,3 - wait for reviewer,3 - work in progress

          # PR
          # days-before-pr-stale: 60
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          stale-pr-label: Stale

          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          # days-before-pr-close: 10
          close-pr-label: Stale

          exempt-pr-labels: 4 - verified,4 - internal Issue/MR,3 - wait for merge,3 - wait for pipeline,3 - wait for reviewer,3 - work in progress